config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  devise_for :users, :controllers => {:registrations => "registrations"}
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated  do
      root to: 'projects#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_path'
    end
  end

  resources :projects do
    member do
      patch  'update_task'
    end
    resources :tasks
  end
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, :dependent => :delete_all

  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :due_date

  enum status: {
      'Complete': 1,
      'Progress': 2,
      'Active': 0

  }
  after_initialize :set_defaults, if: :new_record?

  def set_defaults
    self.status = "Active"
  end

  accepts_nested_attributes_for :tasks, reject_if: lambda { |attributes| attributes['name'].blank? }, allow_destroy: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :task_status
  validates_presence_of :task_date

  enum task_status: {
      'Done': 1,
      'Progress': 2,
      'To Do': 0,
  }
  enum priority: {
      'High': 1,
      'Low': 2,
      'Medium': 3
  }
end                                               

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_user
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def set_user
    @user = current_user
  end

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:role, :name])
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform that action."
    redirect_to(request.referrer || root_path)
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :update_task]


  def index
    if user_signed_in?
      @projects = current_user.projects
    else
      flash[:alert] = "Create Your Project"
    end
  end

  def new
    @project = Project.new
    @project.tasks.build
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      @project
      render :new
    end
  end

  def show
    # @project = Project.find_by(id: params[:id])
  end

  def edit

  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :show
    end
  end
  def update_task
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  ## ADDITIONAL ACTIONS


  ## PRIVATE METHODS

  private

  def set_project
    if params[:id]
      @project = Project.find_by(id: params[:id])
    else
      @project = Project.find_by(id: params[:project_id])
    end
  end

  # def project_statuses_count
  #   @overdue = (current_user.overdue_projects + current_user.collaboration_projects.overdue).uniq.count
  #   @active = (current_user.active_projects + current_user.collaboration_projects.active).uniq.count
  #   @complete = (current_user.complete_projects + current_user.collaboration_projects.complete).uniq.count
  # end

  def project_params
    params.require(:project).permit(:name, :description, :user_id, :due_date, :status,
                                    tasks_attributes: [:name, :description, :task_status, :priority, :task_date, :project_id, :user_id, :_destroy])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :current_password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, except: [:show, :edit]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]


  # GET /tasks
  # GET /tasks.json
  def index
    if user_signed_in?
      @tasks = current_user.tasks
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @project = @task.project
  end

  # GET /tasks/new
  def new
    # @task = Task.new(project: @project)
    @task = @project.tasks.build()
  end

  # GET /tasks/1/edit
  def edit
    # @project = @task.project
  end

  # POST /tasks
  # POST /tasks.json
  def create
    # @task = @project.tasks.new()
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@task.project_id), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    task_status = "task_status_#{@task.id}"
    if Rails.cache.exist?(task_status)
      Rails.cache.delete(task_status)
    end
    Rails.cache.write(task_status, @task)
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_path(@task.project_id), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end





  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@task.project_id), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def set_project
    if params[:id]
      @project = Project.find_by(id: params[:id])
    else
      @project = Project.find_by(id: params[:project_id])
    end
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :description, :task_status, :priority, :task_date, :date, :project_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
        <%= render 'layouts/navigation/header' %>
      </div>
      <div class="col-sm-5">
        <%= render 'layouts/navigation/collapsible_elements' %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
    <% if user_signed_in? %>
      <li class="dropdown pc-menu">
        <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span id="user-name"><%= current_user.name %></span>
          <span class="caret"></span>
        </a>

        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>

      <li class="mobile-menu">
        <%= link_to 'Edit Profile', edit_user_registration_path %>
      </li>
      <li class="mobile-menu">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </li>

    <% else # user not signed it %>
      <li ><%= link_to 'Login', login_path %></li>
      <li ><%= link_to 'Signup', signup_path %></li>
    <% end # if user is signed it %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header col-sm-7">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsible-content" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'New Project', new_project_path, class: 'navbar-brand' %>
</div>

app/views/projects/_form.html.erb
<div class="container">
  <div class="col-sm-8 col-sm-offset-2">
    <%= simple_form_for(@project, local: true) do |f| %>
      <div class="card">
        <div class="card-header">
          <div class="form-group">
            <%= f.label :name, class: "control-label" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description, class: "control-label" %>
            <%= f.text_field :description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :due_date, class: "control-label" %>
            <%= f.date_select :due_date, :order => [:month, :day, :year], class: "form-control" %>
          </div>
          <% if action_name == "new" %>
          <div class="form-group">
            <%= f.label :Task, "Add a Task", class: "control-label" %><br/>
            <%= f.fields_for :tasks do |task_field| %>
              <div class="form-group">
                <%= f.label :task_name, class: "control-label" %>
              <%= task_field.text_field :name, label: 'Title', class: "form-control" %>
              </div>
              <div class="form-group">
              <%= f.label :description, class: "control-label" %>
              <%= task_field.text_area :description, rows: 3, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :Status, class: "control-label" %>
                <%= task_field.select :task_status, Task.task_statuses.keys, {}, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :priority, class: "control-label" %>
                <%= task_field.select :priority, Task.priorities.keys, {}, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :task_due_date, class: "control-label" %>
              <%= task_field.date_select :task_date, :order => [:month, :day, :year], class: "form-control" %>
              </div>
              <%= task_field.hidden_field :user_id, value: @user.id %>
              <%#= task_field.hidden_field :project_id, value: @project.id %>
            <% end %>
          </div>
            <% end %>
        </div>
        <div class="card-footer">
          <div class="form-group text-center">
            <%= f.hidden_field :user_id, value: @user.id %>
            <%= f.submit class: "btn btn-primary btn-block mb-2" %>
          </div>
          <div class="form-group text-center">
            <%= link_to 'Back', projects_path, class: 'btn btn-primary btn-block mb-2' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'form', product: @product %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<ul class="text-info mb-3">
    <h2 class="text-info text-center mb-6">Project List</h2>
</ul>
<div class="container">
  <div class="row">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
        <thead>
        <tr>
          <th>Actions</th>
          <th scope="col">Project</th>
          <th scope="col">Project Name</th>
          <th scope="col">Description</th>
          <th scope="col">Status</th>
          <th scope="col">Due Date</th>
          <th scope="col">Created By</th>
          <th scope="col">Created At</th>
        </tr>
        </thead>
        <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td>
              <a class="btn btn-primary" href="<%=project_path(project) %>" role="button">View</a>
              <a class="btn btn-primary" href="<%=edit_project_path(project) %>" role="button">Edit</a>
              <a class="btn btn-primary" href="<%=project_tasks_path(project) %>" role="button">Task</a>
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
            </td>
            <td><%= project.id%></td>
            <td><%= link_to project.name, project_path(project) %></td>
            <td><%= project.description %></td>
            <td><%= project.status.capitalize %></td>
            <td><%= project.due_date %></td>
            <td><%= project.user.name %></td>
            <td><%= project.created_at %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
  <%= render 'form', product: @product %>

app/views/projects/show.html.erb
<div class="main-container">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
        <section class="pt-3 pt-lg-4 pb-2">
          <div class="d-md-flex justify-content-between">
            <h3 class="display-5 d-flex align-items-center">
              Project Number #<%= @project.id %>
            </h3>
            <a href="<%= edit_project_path(@project) %>" class="btn btn-primary btn-rounded align-self-center btn-block-sm-down"><i class="fal fa-pen mr-1"></i>
              Edit Project</a>
            <a href="<%= new_project_task_path(@project) %>" class="btn btn-primary btn-rounded align-self-center btn-block-sm-down"><i class="fal fa-pen mr-1"></i>
              New Task</a>
          </div>
        </section>
        <h3 class="text-uppercase text-black-50 pb-5 text-center">Product Details</h3></br>
        <div class="card">
          <div class="card-alternative mt-3">
            <div class=form-row>
              <div class="col-6 col-md-4">
                <strong class="d-block">Project Name #</strong>
                <%= @project.name %>
              </div>
              <div class="col-6 col-md-4">
                <strong class="d-block">Description :</strong>
                <%= @project.description %>
              </div>

              <div class="col-6 col-md-4">
                <strong class="d-block">Project Date :</strong>
                <%= @project.due_date %>
              </div>
            </div>
            <div class=form-row>
              <div class="col-6 col-md-4">
                <strong class="d-block">Status</strong>
                <%= @project.status %>
              </div>

              <div class="col-6 col-md-4">
                <strong class="d-block">Created At</strong>
                <%= @project.created_at %>
              </div>
              <div class="col-6 col-md-4">
                <strong class="d-block">Created By</strong>
                <%= @project.user.name %>
              </div>
            </div>
          </div>
        </div>
        <div class="card" style="margin-top: 5%;">
          <% if @project.tasks.present? %>
            <div class="card mb-2">
              <div class="card-body">

                <table class="table table-bordered dt-responsive wrap-whitespace w-100 datatable m-0" data-fixed-header="false" data-sort="false">
                  <thead>
                  <tr>
                    <th class="no-sort">Sr. No.</th>
                    <th class="no-sort">Task</th>
                    <th class="no-sort">description</th>
                    <th class="no-sort">status</th>
                    <th class="no-sort">priority</th>
                    <th class="no-sort">due_date</th>
                    <th class="no-sort">Assigned</th>
                    <th>Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @project.tasks.reverse.each_with_index do |row, sr_no| %>
                    <% if row.project.present? %>

                      <tr>
                        <td><%= sr_no + 1 %></td>
                        <td><%= row.name %> </td>
                        <td><%= row.description %></td>
                        <td><%= row.task_status %></td>
                        <td><%= row.priority %></td>
                        <td><%= row.task_date %></td>
                        <td><%= row.user.name %></td>
                        <td>
                          <a class="btn btn-primary" href="<%= edit_task_path(row) %>" role="button">Edit</a>
                          <%= link_to 'Destroy', row, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary' %>
                          <button type="button" class="btn btn-primary" data-toggle="modal" data-id= "<%= @project.id %>" data-target="#statusModal"x>Update
                            Status
                          </button>
                        </td>
                      </tr>
                    <% end %>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          <% end %>
          <div class="col-6 col-md-3">
            <div class="modal fade" id="statusModal" role="dialog">
              <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title">Update Task</h4>
                  </div>
                  <div class="modal-body">
                    <%= simple_form_for([@project], :url => update_task_project_path(@project)) do |f| %>
                      <div class="error bg-danger text-white mb-3 px-1 rounded"></div>
                      <div class="card">
                        <div class="card-body">
                          <div class="form-row">
                            <div class="col">
                              <%= f.fields_for :tasks, f.object.tasks.build() do |task| %>
                                <%= task.hidden_field :user_id, value: @user.id %>
                                <%=task.hidden_field :project_id%>
                                <%= task.label :task_name, class: "control-label" %>
                                <%= task.text_field :name, label: 'Title', class: "form-control" %>
                                <%= task.label :description, class: "control-label" %>
                                <%= task.text_area :description, rows: 3, class: "form-control" %>
                                <%= task.label :Status, class: "control-label" %>
                                <%= task.select :task_status, Task.task_statuses.keys, {}, class: 'form-control' %>
                                <%= task.label :priority, class: "control-label" %>
                                <%= task.select :priority, Task.priorities.keys, {}, class: 'form-control' %>
                                <%= task.label :task_due_date, class: "control-label" %>
                                <%= task.date_select :task_date, :order => [:month, :day, :year], class: "form-control" %>
                              <% end %>
                            </div>
                          </div>
                          <div class="form-row mb-2 mt-0 ml-0">
                            <button type="submit" class="btn btn-primary">
                              Add Task
                            </button>
                          </div>
                        </div>
                      </div>
                    <% end %>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
        </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
    <div class="container">
      <div class="col-sm-8 col-sm-offset-2">
        <%= simple_form_for(@task, local: true) do |f| %>
          <%= f.hidden_field :user_id, value: @user.id %>
          <%= f.hidden_field :project_id%>
          <div class="form-group">
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <div class="card">
            <div class="card-header">
              <div class="form-group">
                <%= f.label :name, class: "control-label" %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :description, class: "control-label" %>
                <%= f.text_field :description, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :task_status, class: "control-label" %>
                <%= f.select :task_status, Task.task_statuses.keys, {}, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :priority, class: "control-label" %>
                <%= f.select :priority, Task.priorities.keys, {}, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :due_date, class: "control-label" %>
                <%= f.date_select :task_date, :order => [:month, :day, :year], class: "form-control" %>
              </div>
<!--              <div class="form-group">-->
                <%#= f.association :project, include_blank: false, input_html: {class: 'control-label select2-single'} %>
<!--              </div>-->
<!--              <div class="form-group">-->
                <%#= f.association :user, include_blank: false, input_html: {class: 'control-label select2-single'} %>
<!--              </div>-->
            </div>
            <div class="card-footer">
              <div class="form-group text-center">
                <%= f.submit class: "btn btn-primary btn-block mb-2" %>
              </div>
              <div class="form-group text-center">
                 <%= link_to 'Back', tasks_path, class: 'btn btn-primary btn-block mb-2' %>
              </div>
            </div>
          </div>
          </div>
        <% end %>
      </div>
    </div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Due date</th>
      <th>Project</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.task_status %></td>
        <td><%= task.task_date %></td>
        <td><%= task.project.name %></td>
        <td><%= task.user.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1 class="text-center">New Task</h1>
    <%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.task_status %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.task_date %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>